apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-hello
  name: np-app-hello
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30008
  selector:
    app: app-hello
  type: NodePort

