apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-hello
  name: np-svc-app-hello
spec:
  ports:
  - port: 9070
    protocol: TCP
    targetPort: 9070
    nodePort: 30008
  selector:
    app: app-hello
  type: NodePort

