apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-hello
  name: np-app-hello
spec:
  ports:
  - port: 9002
    protocol: TCP
    targetPort: 9002
    nodePort: 30008
  selector:
    app: app-hello
  type: NodePort

